homepage: http://github.com/matthewwithanm/python-markdownify
main_repo: http://github.com/matthewwithanm/python-markdownify
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
vendor_ccs:
- david@adalogics.com
