homepage: https://github.com/spec-first/connexion
main_repo: https://github.com/spec-first/connexion
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
