fuzzing_engines:
- libfuzzer
homepage: https://github.com/dgasmith/opt_einsum
language: python
main_repo: https://github.com/dgasmith/opt_einsum
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
