homepage: https://github.com/tiran/defusedxml
main_repo: https://github.com/tiran/defusedxml
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
