homepage: https://github.com/python-hyper/hyperlink
main_repo: https://github.com/python-hyper/hyperlink
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
vendor_ccs:
- david@adalogics.com
