homepage: "https://bitbucket.org/jpommier/pffft"
main_repo: "https://bitbucket.org/jpommier/pffft.git"
language: c++
primary_contact: "pommier@modartt.com"
auto_ccs:
  - "alessiob@webrtc.org"
  - "mbonadei@webrtc.org"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
  - i386
