homepage: https://github.com/executablebooks/mdurl
main_repo: https://github.com/executablebooks/mdurl
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
