homepage: "https://www.resiprocate.org/"
language: c++
primary_contact: "gjasny@googlemail.com"
main_repo: 'https://github.com/resiprocate/resiprocate.git'

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

