homepage: "https://racket-lang.org"
primary_contact: "pocmatos@gmail.com"
main_repo: "https://github.com/racket/racket/"
auto_ccs:
  - samth@racket-lang.org
sanitizers:
 - undefined
 - memory
 - address
architectures:
 - x86_64
 - i386
