homepage: https://github.com/wtforms/flask-wtf/
main_repo: https://github.com/wtforms/flask-wtf/
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
