homepage: "https://github.com/FFMS/ffms2"
main_repo: "https://github.com/FFMS/ffms2"
language: c++
fuzzing_engines:
- libfuzzer
- honggfuzz
sanitizers:
- address
- undefined
vendor_ccs:
- "david@adalogics.com"
- "arthur.chan@adalogics.com"
