homepage: "https://github.com/xerial/snappy-java/"
language: jvm
primary_contact: ""
fuzzing_engines:
  - "libfuzzer"
sanitizers:
  - "address"
main_repo: "https://github.com/xerial/snappy-java.git"
vendor_ccs:
  - "glendowne@code-intelligence.com"
  - "wagner@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "hlin@code-intelligence.com"
  - "jacek.trossen@code-intelligence.com"
  - "michael.nothhard@code-intelligence.com"
  - "bug-disclosure@code-intelligence.com"
