disabled: true
homepage: http://www.zlib.net/
language: c++
main_repo: https://github.com/madler/zlib
sanitizers:
- address
- memory
- undefined
vendor_ccs: []

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

