fuzzing_engines:
- libfuzzer
homepage: https://github.com/giampaolo/psutil
language: python
main_repo: https://github.com/giampaolo/psutil
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
