homepage: "https://libvnc.github.io/"
language: c++
primary_contact: "dontmind@sdf.org"
auto_ccs:
  - "p.antoine@catenacyber.fr"
  - "info@christianbeier.net"
  - "christian.cb.beier@gmail.com"
main_repo: 'https://github.com/LibVNC/libvncserver.git'
fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer
