homepage: https://github.com/executablebooks/mdit-py-plugins
main_repo: https://github.com/executablebooks/mdit-py-plugins
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
