homepage: "https://github.com/tesseract-ocr/tesseract"
language: c++
primary_contact: "stjoweil@googlemail.com"
main_repo: 'https://github.com/tesseract-ocr/tesseract'

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

