homepage: "https://www.antlr.org"
language: jvm
main_repo: "https://github.com/antlr/antlr3.git"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
vendor_ccs:
- david@adalogics.com
- arthur.chan@adalogics.com
