homepage: "https://github.com/bluez/bluez"
language: c
primary_contact: "bluez.test.bot@gmail.com"
main_repo: "https://github.com/bluez/bluez"
auto_ccs:
  - "hj.tedd.an@gmail.com"
  - "david@adalogics.com"
fuzzing_engines:
  - libfuzzer
  - honggfuzz
  - afl
  # - centipede disabled due to https://github.com/google/oss-fuzz/pull/10248#issuecomment-1579657163
