homepage: https://github.com/cpburnz/python-pathspec
main_repo: https://github.com/cpburnz/python-pathspec
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
