homepage: "https://sourceforge.net/projects/opencsv/"
language: jvm
fuzzing_engines:
  - libfuzzer
main_repo: "https://git.code.sf.net/p/opencsv/source/"
sanitizers:
  - address
vendor_ccs:
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "glendowne@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "hlin@code-intelligence.com"
  - "bug-disclosure@code-intelligence.com"