homepage: "https://github.com/tensorflow/addons"
main_repo: "https://github.com/tensorflow/addons"
language: python
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
vendor_ccs:
- david@adalogics.com
