homepage: "https://hunspell.github.io/"
language: c++
primary_contact: "caolanm@gmail.com"
vendor_ccs:
  - "twsmith@mozilla.com"
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - i386
  - x86_64
main_repo: 'https://github.com/hunspell/hunspell.git'

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

