homepage: "https://github.com/netplex/json-smart-v2"
language: jvm
primary_contact: "uchemouni@gmail.com"
fuzzing_engines:
  - "libfuzzer"
sanitizers:
  - "address"
main_repo: "https://github.com/netplex/json-smart-v2.git"
vendor_ccs:
  - "glendowne@code-intelligence.com"
  - "wagner@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "hlin@code-intelligence.com"
  - "jacek.trossen@code-intelligence.com"
  - "bug-disclosure@code-intelligence.com"
