homepage: "https://github.com/hynek/pem"
language: python
main_repo: "https://github.com/hynek/pem"
fuzzing_engines:
- libfuzzer
sanitizers:
- address
vendor_ccs:
- david@adalogics.com
- adam@adalogics.com
- arthur.chan@adalogics.com
