homepage: "https://github.com/janet-lang/janet"
primary_contact: "calsrose@gmail.com"
language: c++
auto_ccs:
  - "david@adalogics.com"
main_repo: 'https://github.com/janet-lang/janet'

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

