fuzzing_engines:
- libfuzzer
homepage: https://github.com/python/importlib_metadata
language: python
main_repo: https://github.com/python/importlib_metadata
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
