homepage: https://github.com/kislyuk/argcomplete
main_repo: https://github.com/kislyuk/argcomplete
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
