homepage: "https://cxf.apache.org/"
language: jvm
main_repo: "https://github.com/apache/cxf/"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
vendor_ccs:
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "glendowne@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "hlin@code-intelligence.com"
  - "bug-disclosure@code-intelligence.com"