homepage: https://www.pycryptodome.org/
language: c
main_repo: https://github.com/Legrandin/pycryptodome.git
primary_contact: helderijs@gmail.com

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

