homepage: https://github.com/mpdavis/python-jose
main_repo: https://github.com/mpdavis/python-jose
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
vendor_ccs:
- david@adalogics.com
