homepage: "https://mosquitto.org/"
language: c
primary_contact: "roger@atchoo.org"
auto_ccs:
 - "security@eclipse.org"
 - "rogerlight@gmail.com"
sanitizers:
 - address
 - memory:
    experimental: True
 - undefined
main_repo: 'https://github.com/eclipse/mosquitto'

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

