homepage: "https://perfetto.dev"
language: c++
primary_contact: "hjd@google.com"
auto_ccs:
  - "hjd@google.com"
  - "lalitm@google.com"
  - "octaviant@google.com"
  - "perfetto-oss-fuzz@google.com"
  - "primiano@google.com"
  - "rsavitski@google.com"
  - "eseckler@google.com"
  - "altimin@google.com"
  - "ddiproietto@google.com"
vendor_ccs:
  - adambacchus@google.com
  - ailport@google.com
  - bcreasey@google.com
  - cunefare@google.com
  - ejorgensen@google.com
  - faerber@google.com
  - greendonald@google.com
  - hamzeh@google.com
  - jaredkidd@google.com
  - kimtony@google.com
  - lindsaywells@google.com
  - maverickm@google.com
  - swansonr@google.com
  - warrenwright@google.com
sanitizers:
  - address
  - undefined
main_repo: 'https://android.googlesource.com/platform/external/perfetto/'
