homepage: https://github.com/erikrose/parsimonious
main_repo: https://github.com/erikrose/parsimonious
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
vendor_ccs:
- david@adalogics.com
