homepage: https://github.com/jaraco/configparser/
main_repo: https://github.com/jaraco/configparser/
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
vendor_ccs:
- david@adalogics.com
