fuzzing_engines:
- libfuzzer
homepage: https://github.com/PythonCharmers/python-future
language: python
main_repo: https://github.com/PythonCharmers/python-future
sanitizers:
- address
vendor_ccs:
- david@adalogics.com
