homepage: https://github.com/jupyter/nbclassic
main_repo: https://github.com/jupyter/nbclassic
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
