homepage: "https://dapr.io/"
language: go
primary_contact: "schneideryaron@gmail.com"
main_repo: "https://github.com/dapr"
auto_ccs:
  - "artur04@gmail.com"
vendor_ccs:
  - "adam@adalogics.com"
  - "david@adalogics.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
