homepage: https://github.com/jupyter/nbformat
main_repo: https://github.com/jupyter/nbformat
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
