homepage: "https://github.com/zlib-ng/zlib-ng"
language: c++
primary_contact: "zlib-ng@circlestorm.org"
auto_ccs:
  - "sebpop@gmail.com"
  - "nathan.moinvaziri@gmail.com"
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
  - i386
fuzzing_engines:
  - libfuzzer
  - honggfuzz
  - afl
  # - centipede disabled due to https://github.com/google/oss-fuzz/pull/10248#issuecomment-1579657163
main_repo: 'https://github.com/zlib-ng/zlib-ng.git'
