homepage: "https://github.com/fsnotify/fsnotify"
language: go
main_repo: "https://github.com/fsnotify/fsnotify"
auto_ccs:
  - "adam@adalogics.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
