homepage: "https://github.com/mdbtools/mdbtools"
language: c
primary_contact: "emmiller@gmail.com"
main_repo: "https://github.com/mdbtools/mdbtools"

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

