homepage: "https://github.com/kjdev/hoextdown"
language: c++
primary_contact: "kjclev@gmail.com"
main_repo: 'https://github.com/kjdev/hoextdown.git'

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

