homepage: https://github.com/necaris/python3-openid
main_repo: https://github.com/necaris/python3-openid
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
