homepage: "https://github.com/google/go-cmp/cmp"
language: go
main_repo: "https://github.com/google/go-cmp/cmp"
auto_ccs:
  - "adam@adalogics.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
