homepage: https://github.com/tlsfuzzer/python-ecdsa
main_repo: https://github.com/tlsfuzzer/python-ecdsa
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
