homepage: https://github.com/wtforms/wtforms
main_repo: https://github.com/wtforms/wtforms
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
