homepage: "https://www.xpdfreader.com/"
primary_contact: "xpdf@xpdfreader.com"
language: c++
sanitizers:
  - address
auto_ccs :
  - "david@adalogics.com"

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

