homepage: "https://www.tensorflow.org"
language: c++
primary_contact: "lpak@google.com"
auto_ccs:
 - "itaiz@google.com"
 - "mihaimaruseac@google.com"
 - "rostam@google.com"
 - "unda@google.com"
 - "david@adalogics.com"
sanitizers:
  - address
  - undefined
fuzzing_engines:
  - libfuzzer
main_repo: 'https://github.com/tensorflow/tensorflow'
