homepage: "https://github.com/DaveGamble/cJSON"
language: c++
primary_contact: "max@maxbruckner.de"
auto_ccs:
  - "randy440088@gmail.com"
  - "wp_scut@163.com"
sanitizers:
  - address
  - undefined
  - memory
main_repo: 'https://github.com/DaveGamble/cJSON.git'
