homepage: "developers.google.com/identity"
language: jvm
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/googleapis/google-auth-library-java/"
sanitizers:
  - address
vendor_ccs:
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "hlin@code-intelligence.com"
  - "bug-disclosure@code-intelligence.com"