fuzzing_engines:
- libfuzzer
homepage: https://github.com/python-hyper/uritemplate
language: python
main_repo: https://github.com/python-hyper/uritemplate
sanitizers:
- address
vendor_ccs:
- david@adalogics.com
