homepage: "https://github.com/gimli-rs/gimli"
language: rust
primary_contact: "philipjcraig@gmail.com"
main_repo: "https://github.com/gimli-rs/gimli"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
vendor_ccs:
  - maxnair.dev@gmail.com
