homepage: "https://github.com/googleapis/google-http-java-client/"
language: jvm
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/googleapis/google-http-java-client/"
sanitizers:
  - address
vendor_ccs:
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "glendowne@code-intelligence.com"
  - "hlin@code-intelligence.com"
  - "bug-disclosure@code-intelligence.com"