homepage: "https://github.com/serde-rs/json"
primary_contact: "dtolnay@gmail.com"
main_repo: "https://github.com/serde-rs/json"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
language: rust
auto_ccs:
  - "david@adalogics.com"
