homepage: "https://xerces.apache.org/index.html"
language: jvm
main_repo: "http://svn.apache.org/repos/asf/xerces/java/trunk"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
vendor_ccs:
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "glendowne@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "hlin@code-intelligence.com"
  - "schaich@code-intelligence.com"
  - "jacek.trossen@code-intelligence.com"
  - "bug-disclosure@code-intelligence.com"