homepage: https://github.com/arrow-py/arrow
main_repo: https://github.com/arrow-py/arrow
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
primary_contact: me@krisfremen.com
vendor_ccs:
- david@adalogics.com
