homepage: https://github.com/encode/httpcore
main_repo: https://github.com/encode/httpcore
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
