homepage: https://github.com/xflr6/graphviz
main_repo: https://github.com/xflr6/graphviz
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
