homepage: "https://github.com/dustin/go-humanize"
language: go
main_repo: "https://github.com/dustin/go-humanize"
auto_ccs:
  - "adam@adalogics.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
