homepage: "https://www.knot-dns.cz/"
main_repo: "https://gitlab.nic.cz/knot/knot-dns.git"
language: c++
primary_contact: "knot.dns@gmail.com"
auto_ccs:
  - "jonathan.foote@gmail.com"
sanitizers:
  - address
  - memory
  - undefined

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

