fuzzing_engines:
- libfuzzer
homepage: https://github.com/sdispater/pendulum
language: python
main_repo: https://github.com/sdispater/pendulum
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
