fuzzing_engines:
- libfuzzer
homepage: https://github.com/redis/hiredis-py
language: python
main_repo: https://github.com/redis/hiredis-py
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
