homepage: "https://github.com/paul-hammant/qdox/"
language: jvm
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/paul-hammant/qdox/"
sanitizers:
  - address
vendor_ccs:
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "hlin@code-intelligence.com"
  - "bug-disclosure@code-intelligence.com"