homepage: "https://sourceforge.net/projects/faac"
main_repo: "https://github.com/knik0/faad2"
language: c
primary_contact: "eustas@chromium.org"
auto_ccs:
 - "david@adalogics.com"
sanitizers:
 - address
 - memory
 - undefined
